
def region(r):

    r = r.replace('Alto Adige', 'Alto-Adigio').replace('Rías Baixas', 'Rias Baixas').replace('Costers del Segre',
                    'Costers del Sagre'). replace('Valle de Uco','Uco Valley').replace('Valle del Maipo',
                    'Maipo Valley').replace('Terra Alta',
                    'Terre Alta').replace('Washington State', 'Washington').replace('I.G.', 'IG').replace(
                    'Pago Vallegarcía', 'Pago Vallegarcia').replace('Utiel - Requena', 'Utiel-Requena').replace(
                    'Premier Cru', '').replace('Valle de Güímar', 'Valle de Gueimar').strip()


    region_list = [
        {'Country': 'Argentina', 'Region': 'Rio Negro', 'Subregion': 'Alto Valle del Río Negro'},
        {'Country': 'Argentina', 'Region': 'Mendoza', 'Subregion': 'Mendoza'},
        {'Country': 'Argentina', 'Region': 'Mendoza', 'Subregion': 'Uco Valley'},
        {'Country': 'Argentina', 'Region': 'Patagonia', 'Subregion': 'Patagonia'},
        {'Country': 'Argentina', 'Region': 'Salta', 'Subregion': 'Salta'},
        {'Country': 'Argentina', 'Region': 'San Juan', 'Subregion': 'San Juan'},
        {'Country': 'Australia', 'Region': 'South Australia', 'Subregion': 'Barossa Valley'},
        {'Country': 'Australia', 'Region': 'South Australia', 'Subregion': 'Clare Valley'},
        {'Country': 'Australia', 'Region': 'South Australia', 'Subregion': 'McLaren Vale'},
        {'Country': 'Australia', 'Region': 'Victoria', 'Subregion': 'Heathcote'},
        {'Country': 'Austria', 'Region': 'Niederoesterreich', 'Subregion': 'Kamptal'},
        {'Country': 'Canada', 'Region': 'Ontario', 'Subregion': 'Niagara-on-the-Lake'},
        {'Country': 'Chile', 'Region': 'Atacama', 'Subregion': 'Atacama' },
        {'Country': 'Chile', 'Region': 'Biobio', 'Subregion': 'Guarilehue'},
        {'Country': 'Chile', 'Region': 'Biobio', 'Subregion': 'Valle de Itata'},
        {'Country': 'Chile', 'Region': 'Central Valley', 'Subregion': 'Valle Central'},
        {'Country': 'Chile', 'Region': 'Valparaiso', 'Subregion': 'Valle de Casablanca'},
        {'Country': 'Chile', 'Region': 'Valparaiso', 'Subregion': 'Valle del Aconcagua'},
        {'Country': 'Chile', 'Region': 'Coquimdo', 'Subregion': 'Choapa Valley'},
        {'Country': 'Chile', 'Region': 'Coquimdo', 'Subregion': 'Limari Valley'},
        {'Country': 'Chile', 'Region': 'Ohiggins', 'Subregion': 'Valle de Cachapoal'},
        {'Country': 'Chile', 'Region': 'Ohiggins', 'Subregion': 'Colchagua Valley'},
        {'Country': 'Chile', 'Region': 'Ohiggins', 'Subregion': 'Rapel Valley'},
        {'Country': 'Chile', 'Region': 'Maule', 'Subregion': 'Valle de Curicó'},
        {'Country': 'Chile', 'Region': 'Maule', 'Subregion': 'Maule Valley'},
        {'Country': 'Chile', 'Region': 'Santiago', 'Subregion': 'Maipo Valley'},
        {'Country': 'Croatia', 'Region': 'Slavonia', 'Subregion': 'Kutjevo'},
        {'Country': 'Croatia', 'Region': 'Split', 'Subregion': 'Srednja I Južna Dalmacija'},
        {'Country': 'France', 'Region': 'Alsace', 'Subregion': 'Alsace'},
        {'Country': 'France', 'Region': 'Alsace', 'Subregion': "Crémant d'Alsace"},
        {'Country': 'France', 'Region': 'Bordeaux', 'Subregion': 'Blaye Côtes de Bordeaux'},
        {'Country': 'France', 'Region': 'Bordeaux', 'Subregion': 'Bordeaux'},
        {'Country': 'France', 'Region': 'Bordeaux', 'Subregion': 'Bordeaux Rosé'},
        {'Country': 'France', 'Region': 'Bordeaux', 'Subregion': 'Bordeaux Supérieur'},
        {'Country': 'France', 'Region': 'Bordeaux', 'Subregion': 'Cadillac-Côtes de Bordeaux'},
        {'Country': 'France', 'Region': 'Bordeaux', 'Subregion': 'Castillon-Côtes de Bordeaux'},
        {'Country': 'France', 'Region': 'Bordeaux', 'Subregion': 'Côtes de Bourg'},
        {'Country': 'France', 'Region': 'Bordeaux', 'Subregion': 'Côtes de Bordeaux'},
        {'Country': 'France', 'Region': 'Bordeaux', 'Subregion': 'Entre Deux Mers'},
        {'Country': 'France', 'Region': 'Bordeaux', 'Subregion': 'Graves'},
        {'Country': 'France', 'Region': 'Bordeaux', 'Subregion': 'Haut-Médoc'},
        {'Country': 'France', 'Region': 'Bordeaux', 'Subregion': 'Lalande-de-Pomerol'},
        {'Country': 'France', 'Region': 'Bordeaux', 'Subregion': 'Margaux'},
        {'Country': 'France', 'Region': 'Bordeaux', 'Subregion': 'Médoc'},
        {'Country': 'France', 'Region': 'Bordeaux', 'Subregion': 'Montagne Saint-Emilion'},
        {'Country': 'France', 'Region': 'Bordeaux', 'Subregion': 'Pauillac'},
        {'Country': 'France', 'Region': 'Bordeaux', 'Subregion': 'Pessac-Léognan'},
        {'Country': 'France', 'Region': 'Bordeaux', 'Subregion': 'Pomerol'},
        {'Country': 'France', 'Region': 'Bordeaux', 'Subregion': 'Premières Côtes de Bordeaux'},
        {'Country': 'France', 'Region': 'Bordeaux', 'Subregion': 'Saint-Emilion'},
        {'Country': 'France', 'Region': 'Bordeaux', 'Subregion': 'Saint-Estèphe'},
        {'Country': 'France', 'Region': 'Bordeaux', 'Subregion': 'Saint-Julien'},
        {'Country': 'France', 'Region': 'Bordeaux', 'Subregion': 'Sauternes e Barsac'},
        {'Country': 'France', 'Region': 'Burgundy', 'Subregion': 'Auxey-Duresses'},
        {'Country': 'France', 'Region': 'Burgundy', 'Subregion': 'Beaujolais'},
        {'Country': 'France', 'Region': 'Burgundy', 'Subregion': 'Beaune'},
        {'Country': 'France', 'Region': 'Burgundy', 'Subregion': 'Bourgogne'},
        {'Country': 'France', 'Region': 'Burgundy', 'Subregion': 'Bourgogne Aligoté'},
        {'Country': 'France', 'Region': 'Burgundy', 'Subregion': 'Bourgogne-Hautes-Côtes-de-Nuits'},
        {'Country': 'France', 'Region': 'Burgundy', 'Subregion': 'Bouzeron'},
        {'Country': 'France', 'Region': 'Burgundy', 'Subregion': 'Chablis'},
        {'Country': 'France', 'Region': 'Burgundy', 'Subregion': 'Chambolle-Musigny'},
        {'Country': 'France', 'Region': 'Burgundy', 'Subregion': 'Chassagne Montrachet'},
        {'Country': 'France', 'Region': 'Burgundy', 'Subregion': 'Chorey-les-Beaune'},
        {'Country': 'France', 'Region': 'Burgundy', 'Subregion': 'Clos de Vougeot'},
        {'Country': 'France', 'Region': 'Burgundy', 'Subregion': 'Corton'},
        {'Country': 'France', 'Region': 'Burgundy', 'Subregion': 'Coteaux Bourguignons'},
        {'Country': 'France', 'Region': 'Burgundy', 'Subregion': 'Crémant de Bourgogne'},
        {'Country': 'France', 'Region': 'Burgundy', 'Subregion': 'Côte de Brouilly'},
        {'Country': 'France', 'Region': 'Burgundy', 'Subregion': 'Côte de Nuits-Villages'},
        {'Country': 'France', 'Region': 'Burgundy', 'Subregion': 'Fixin'},
        {'Country': 'France', 'Region': 'Burgundy', 'Subregion': 'Fleurie'},
        {'Country': 'France', 'Region': 'Burgundy', 'Subregion': 'Gevrey Chambertin'},
        {'Country': 'France', 'Region': 'Burgundy', 'Subregion': 'Gevrey-Chambertin 1er Cru Petite Chapelle'},
        {'Country': 'France', 'Region': 'Burgundy', 'Subregion': 'Hautes-Côtes de Beaune'},
        {'Country': 'France', 'Region': 'Burgundy', 'Subregion': 'Juliénas'},
        {'Country': 'France', 'Region': 'Burgundy', 'Subregion': 'Ladoix'},
        {'Country': 'France', 'Region': 'Burgundy', 'Subregion': 'Maranges'},
        {'Country': 'France', 'Region': 'Burgundy', 'Subregion': 'Marsannay'},
        {'Country': 'France', 'Region': 'Burgundy', 'Subregion': 'Mercurey'},
        {'Country': 'France', 'Region': 'Burgundy', 'Subregion': 'Meursault'},
        {'Country': 'France', 'Region': 'Burgundy', 'Subregion': 'Monthelie'},
        {'Country': 'France', 'Region': 'Burgundy', 'Subregion': 'Monthelie Prmier Cru'},
        {'Country': 'France', 'Region': 'Burgundy', 'Subregion': 'Morgon'},
        {'Country': 'France', 'Region': 'Burgundy', 'Subregion': 'Moulin-à-Vent'},
        {'Country': 'France', 'Region': 'Burgundy', 'Subregion': 'Mâcon'},
        {'Country': 'France', 'Region': 'Burgundy', 'Subregion': 'Mâcon Cruzille'},
        {'Country': 'France', 'Region': 'Burgundy', 'Subregion': 'Mâcon-Bray'},
        {'Country': 'France', 'Region': 'Burgundy', 'Subregion': 'Mâcon-Bussières'},
        {'Country': 'France', 'Region': 'Burgundy', 'Subregion': 'Mâcon-Chardonnay'},
        {'Country': 'France', 'Region': 'Burgundy', 'Subregion': 'Mâcon-Uchizy'},
        {'Country': 'France', 'Region': 'Burgundy', 'Subregion': 'Mâcon-Verzé'},
        {'Country': 'France', 'Region': 'Burgundy', 'Subregion': 'Mâcon-Villages'},
        {'Country': 'France', 'Region': 'Burgundy', 'Subregion': 'Nuits-Saint-Georges'},
        {'Country': 'France', 'Region': 'Burgundy', 'Subregion': 'Pernand-Vergelesses'},
        {'Country': 'France', 'Region': 'Burgundy', 'Subregion': 'Pommard'},
        {'Country': 'France', 'Region': 'Burgundy', 'Subregion': 'Pommard 1er Cru La Platière'},
        {'Country': 'France', 'Region': 'Burgundy', 'Subregion': 'Pouilly-Fuissé'},
        {'Country': 'France', 'Region': 'Burgundy', 'Subregion': 'Pouilly-Vinzelles'},
        {'Country': 'France', 'Region': 'Burgundy', 'Subregion': 'Puligny-Montrachet'},
        {'Country': 'France', 'Region': 'Burgundy', 'Subregion': 'Puligny-Montrachet 1er Cru'},
        {'Country': 'France', 'Region': 'Burgundy', 'Subregion': 'Saint Romain'},
        {'Country': 'France', 'Region': 'Burgundy', 'Subregion': 'Saint Véran'},
        {'Country': 'France', 'Region': 'Burgundy', 'Subregion': 'Saint-Aubin'},
        {'Country': 'France', 'Region': 'Burgundy', 'Subregion': 'Saint-Aubin 1er Cru'},
        {'Country': 'France', 'Region': 'Burgundy', 'Subregion': 'Santenay'},
        {'Country': 'France', 'Region': 'Burgundy', 'Subregion': 'Santenay 1er Cru Beaurepaire'},
        {'Country': 'France', 'Region': 'Burgundy', 'Subregion': 'Savigny-les-Beaune'},
        {'Country': 'France', 'Region': 'Burgundy', 'Subregion': 'Viré-Clessé'},
        {'Country': 'France', 'Region': 'Burgundy', 'Subregion': 'Volnay'},
        {'Country': 'France', 'Region': 'Burgundy', 'Subregion': 'Volnay 1er Cru'},
        {'Country': 'France', 'Region': 'Burgundy', 'Subregion': 'Vosne-Romanée'},
        {'Country': 'France', 'Region': 'Burgundy', 'Subregion': 'Vougeot'},
        {'Country': 'France', 'Region': 'Cahors', 'Subregion': 'Cahors'},
        {'Country': 'France', 'Region': 'Champagne', 'Subregion': 'Champagne'},
        {'Country': 'France', 'Region': 'Champagne', 'Subregion': 'Coteaux Champenois'},
        {'Country': 'France', 'Region': 'France', 'Subregion': 'Vin de France'},
        {'Country': 'France', 'Region': 'Jura', 'Subregion': 'Château Chalon'},
        {'Country': 'France', 'Region': 'Jura', 'Subregion': 'Crémant du Jura'},
        {'Country': 'France', 'Region': 'Jura', 'Subregion': 'Côtes du Jura'},
        {'Country': 'France', 'Region': 'Jura', 'Subregion': "L'Étoile"},
        {'Country': 'France', 'Region': 'Languedoc-Roussillon', 'Subregion': 'Corbières'},
        {'Country': 'France', 'Region': 'Languedoc-Roussillon', 'Subregion': 'Côtes du Roussillon'},
        {'Country': 'France', 'Region': 'Languedoc-Roussillon', 'Subregion': 'Côtes du Roussillon Villages'},
        {'Country': 'France', 'Region': 'Languedoc-Roussillon', 'Subregion': 'Faugères'},
        {'Country': 'France', 'Region': 'Languedoc-Roussillon', 'Subregion': 'Fitou'},
        {'Country': 'France', 'Region': 'Languedoc-Roussillon', 'Subregion': 'IGP Côte Vermeille'},
        {'Country': 'France', 'Region': 'Languedoc-Roussillon', 'Subregion': 'IGP Côtes Catalanes'},
        {'Country': 'France', 'Region': 'Languedoc-Roussillon', 'Subregion': 'IGP Pays d´Oc'},
        {'Country': 'France', 'Region': 'Languedoc-Roussillon', 'Subregion': 'Languedoc'},
        {'Country': 'France', 'Region': 'Languedoc-Roussillon', 'Subregion': 'Languedoc Saint Drézéry'},
        {'Country': 'France', 'Region': 'Languedoc-Roussillon', 'Subregion': 'Limoux'},
        {'Country': 'France', 'Region': 'Languedoc-Roussillon', 'Subregion': 'Maury Sec'},
        {'Country': 'France', 'Region': 'Languedoc-Roussillon', 'Subregion': 'Minervois'},
        {'Country': 'France', 'Region': 'Languedoc-Roussillon', 'Subregion': 'Muscat-de-Saint-Jean-de-Minervois'},
        {'Country': 'France', 'Region': 'Languedoc-Roussillon', 'Subregion': 'Pic Saint Loup'},
        {'Country': 'France', 'Region': 'Languedoc-Roussillon', 'Subregion': "Vin de Pays de l'Hérault"},
        {'Country': 'France', 'Region': 'Loire', 'Subregion': 'Anjou'},
        {'Country': 'France', 'Region': 'Loire', 'Subregion': 'Anjou Villages'},
        {'Country': 'France', 'Region': 'Loire', 'Subregion': 'Bourgueil'},
        {'Country': 'France', 'Region': 'Loire', 'Subregion': 'Chinon'},
        {'Country': 'France', 'Region': 'Loire', 'Subregion': 'Coteaux-du-Layon'},
        {'Country': 'France', 'Region': 'Loire', 'Subregion': 'Coteaux-du-Layon Premier Cru Chaume'},
        {'Country': 'France', 'Region': 'Loire', 'Subregion': 'Loire'},
        {'Country': 'France', 'Region': 'Loire', 'Subregion': 'Pouilly-Fumé'},
        {'Country': 'France', 'Region': 'Loire', 'Subregion': 'Quarts de Chaume Grand Cru'},
        {'Country': 'France', 'Region': 'Loire', 'Subregion': 'Saint-Véran'},
        {'Country': 'France', 'Region': 'Loire', 'Subregion': 'Sancerre'},
        {'Country': 'France', 'Region': 'Loire', 'Subregion': 'Saumur'},
        {'Country': 'France', 'Region': 'Loire', 'Subregion': 'Savennières'},
        {'Country': 'France', 'Region': 'Loire', 'Subregion': 'Vouvrey'},
        {'Country': 'France', 'Region': 'Provence', 'Subregion': 'Bandol'},
        {'Country': 'France', 'Region': 'Provence', 'Subregion': "Coteaux d'Aix-en-Provence"},
        {'Country': 'France', 'Region': 'Provence', 'Subregion': 'Coteaux Varois en Provence'},
        {'Country': 'France', 'Region': 'Provence', 'Subregion': 'Côtes de Provence'},
        {'Country': 'France', 'Region': 'Provence', 'Subregion': 'Côtes de Provence Sainte Victoire'},
        {'Country': 'France', 'Region': 'Provence', 'Subregion': 'IGP Méditerranée'},
        {'Country': 'France', 'Region': 'Provence', 'Subregion': 'IGP Méditerranée Rosé'},
        {'Country': 'France', 'Region': 'Provence', 'Subregion': 'Provence'},
        {'Country': 'France', 'Region': 'Rhône', 'Subregion': 'Beaumes de Venise'},
        {'Country': 'France', 'Region': 'Rhône', 'Subregion': 'Cairanne'},
        {'Country': 'France', 'Region': 'Rhône', 'Subregion': 'Chiroubles'},
        {'Country': 'France', 'Region': 'Rhône', 'Subregion': 'Châteauneuf-du-Pape'},
        {'Country': 'France', 'Region': 'Rhône', 'Subregion': 'Condrieu'},
        {'Country': 'France', 'Region': 'Rhône', 'Subregion': 'Cornas'},
        {'Country': 'France', 'Region': 'Rhône', 'Subregion': 'Costières de Nîmes'},
        {'Country': 'France', 'Region': 'Rhône', 'Subregion': 'Coteaux de l''Ardèche'},
        {'Country': 'France', 'Region': 'Rhône', 'Subregion': 'Crozes-Hermitage'},
        {'Country': 'France', 'Region': 'Rhône', 'Subregion': 'Côte-Rôtie'},
        {'Country': 'France', 'Region': 'Rhône', 'Subregion': 'Côtes du Rhône'},
        {'Country': 'France', 'Region': 'Rhône', 'Subregion': 'Côtes du Rhône Village'},
        {'Country': 'France', 'Region': 'Rhône', 'Subregion': 'Duché d’Uzès'},
        {'Country': 'France', 'Region': 'Rhône', 'Subregion': 'Hermitage'},
        {'Country': 'France', 'Region': 'Rhône', 'Subregion': 'Gigondas'},
        {'Country': 'France', 'Region': 'Rhône', 'Subregion': 'IGP Ardèche'},
        {'Country': 'France', 'Region': 'Rhône', 'Subregion': 'IGP Collines Rhodaniennes'},
        {'Country': 'France', 'Region': 'Rhône', 'Subregion': 'IGP Gard'},
        {'Country': 'France', 'Region': 'Rhône', 'Subregion': 'Lirac'},
        {'Country': 'France', 'Region': 'Rhône', 'Subregion': 'Régnié'},
        {'Country': 'France', 'Region': 'Rhône', 'Subregion': 'Saint-Joseph'},
        {'Country': 'France', 'Region': 'Rhône', 'Subregion': 'Saint-Péray'},
        {'Country': 'France', 'Region': 'Rhône', 'Subregion': 'Tavol'},
        {'Country': 'France', 'Region': 'Rhône', 'Subregion': 'Vacqueyras'},
        {'Country': 'France', 'Region': 'Rhône', 'Subregion': 'Vaucluse'},
        {'Country': 'France', 'Region': 'Rhône', 'Subregion': 'Ventoux'},
        {'Country': 'France', 'Region': 'Rhône', 'Subregion': 'Vinsobres'},
        {'Country': 'Germany', 'Region': 'Baden-Wuerttemberg', 'Subregion': 'Baden'},
        {'Country': 'Germany', 'Region': 'Bayern', 'Subregion': 'Franken'},
        {'Country': 'Germany', 'Region': 'Rheinland-Pfalz', 'Subregion': 'Mosel'},
        {'Country': 'Germany', 'Region': 'Rheinland-Pfalz', 'Subregion': 'Nahe'},
        {'Country': 'Germany', 'Region': 'Rheinland-Pfalz', 'Subregion': 'Pfalz'},
        {'Country': 'Germany', 'Region': 'Rheinland-Pfalz', 'Subregion': 'Rheinhessen'},
        {'Country': 'Germany', 'Region': 'Hessen', 'Subregion': 'Rheingau'},
        {'Country': 'Greece', 'Region': 'Macedonia', 'Subregion': 'Epanomi'},
        {'Country': 'Hungary', 'Region': 'Tokaji', 'Subregion': 'Tokaji'},
        {'Country': 'Israel', 'Region': 'Israel', 'Subregion': 'Galilea'},
        {'Country': 'Israel', 'Region': 'Israel', 'Subregion': 'Galilea Superior'},
        {'Country': 'Italy', 'Region': 'Abruzzo', 'Subregion': 'Abruzzo'},
        {'Country': 'Italy', 'Region': 'Abruzzo', 'Subregion': 'Abruzzo Pecorino' },
        {'Country': 'Italy', 'Region': 'Abruzzo', 'Subregion': "Trebbiano d'Abruzzo"},
        {'Country': 'Italy', 'Region': 'Emilia-Romagna', 'Subregion': 'Lambrusco'},
        {'Country': 'Italy', 'Region': 'Friuli-Venezia-Giulia', 'Subregion': 'Collio - Tenuta di Vencò'},
        {'Country': 'Italy', 'Region': 'Friuli-Venezia-Giulia', 'Subregion': 'Friuli'},
        {'Country': 'Italy', 'Region': 'Friuli-Venezia-Giulia', 'Subregion': 'Friuli Colli Orientali'},
        {'Country': 'Italy', 'Region': 'Friuli-Venezia-Giulia', 'Subregion': 'Friuli Grave'},
        {'Country': 'Italy', 'Region': 'Friuli-Venezia-Giulia', 'Subregion': 'Friuli Isonzo'},
        {'Country': 'Italy', 'Region': 'Friuli-Venezia-Giulia', 'Subregion': 'IGT Venezia Giulia'},
        {'Country': 'Italy', 'Region': 'Friuli-Venezia-Giulia', 'Subregion': 'Venezia'},
        {'Country': 'Italy', 'Region': 'Lombardia', 'Subregion': 'Franciacorta'},
        {'Country': 'Italy', 'Region': 'Lombardia', 'Subregion': 'Lombardia'},
        {'Country': 'Italy', 'Region': 'Lombardia', 'Subregion': 'Lugana'},
        {'Country': 'Italy', 'Region': 'Piedmont', 'Subregion': 'Barbaresco'},
        {'Country': 'Italy', 'Region': 'Piedmont', 'Subregion': 'Barbera d''Alba'},
        {'Country': 'Italy', 'Region': 'Piedmont', 'Subregion': 'Barolo'},
        {'Country': 'Italy', 'Region': 'Piedmont', 'Subregion': "Dolcetto Di Diano D'Alba"},
        {'Country': 'Italy', 'Region': 'Piedmont', 'Subregion': 'Langhe Nebbiolo'},
        {'Country': 'Italy', 'Region': 'Piedmont', 'Subregion': "Moscato d'Asti"},
        {'Country': 'Italy', 'Region': 'Piedmont', 'Subregion': 'Piemonte'},
        {'Country': 'Italy', 'Region': 'Puglia', 'Subregion': 'Salento'},
        {'Country': 'Italy', 'Region': 'Sicily', 'Subregion': 'Etna'},
        {'Country': 'Italy', 'Region': 'Sicily', 'Subregion': 'Sicilia'},
        {'Country': 'Italy', 'Region': 'Sicily', 'Subregion': 'Sicilia Fiano'},
        {'Country': 'Italy', 'Region': 'Sicily', 'Subregion': 'Terre Siciliane'},
        {'Country': 'Italy', 'Region': 'Trentino - Alto-Adigio', 'Subregion': 'Alto-Adigio'},
        {'Country': 'Italy', 'Region': 'Trentino - Alto-Adigio', 'Subregion': 'Vigneti delle Dolomiti'},
        {'Country': 'Italy', 'Region': 'Tuscany', 'Subregion': 'Bolgheri'},
        {'Country': 'Italy', 'Region': 'Tuscany', 'Subregion': 'Brunello di Montalcino'},
        {'Country': 'Italy', 'Region': 'Tuscany', 'Subregion': 'Chianti'},
        {'Country': 'Italy', 'Region': 'Tuscany', 'Subregion': 'Chianti Classico'},
        {'Country': 'Italy', 'Region': 'Tuscany', 'Subregion': 'Maremma'},
        {'Country': 'Italy', 'Region': 'Tuscany', 'Subregion': 'Morellino di Scansano'},
        {'Country': 'Italy', 'Region': 'Tuscany', 'Subregion': 'Toscana'},
        {'Country': 'Italy', 'Region': 'Umbria', 'Subregion': 'Montefalco'},
        {'Country': 'Italy', 'Region': 'Umbria', 'Subregion': 'Montefalco Sagrantino'},
        {'Country': 'Italy', 'Region': 'Umbria', 'Subregion': 'Orvieto Classico'},
        {'Country': 'Italy', 'Region': 'Veneto', 'Subregion': 'Arcole'},
        {'Country': 'Italy', 'Region': 'Veneto', 'Subregion': 'Delle Venezie'},
        {'Country': 'Italy', 'Region': 'Veneto', 'Subregion': 'Valdobbiadene'},
        {'Country': 'Italy', 'Region': 'Veneto', 'Subregion': 'Valpolicella'},
        {'Country': 'Italy', 'Region': 'Veneto', 'Subregion': 'Veneto'},
        {'Country': 'Lebanon', 'Region': 'Bekaa', 'Subregion': 'Bekaa Valley'},
        {'Country': 'New Zealand', 'Region': 'Auckland', 'Subregion': 'Auckland'},
        {'Country': 'New Zealand', 'Region': 'Canterbury', 'Subregion': 'Waipara Valley'},
        {'Country': 'New Zealand', 'Region': 'Otago', 'Subregion': 'Central Otago'},
        {'Country': 'New Zealand', 'Region': 'Gisborne', 'Subregion': 'Gisborne'},
        {'Country': 'New Zealand', 'Region': 'Hawkes Bay', 'Subregion': "Hawke's Bay"},
        {'Country': 'New Zealand', 'Region': 'Marlborough', 'Subregion': 'Marlborough'},
        {'Country': 'New Zealand', 'Region': 'Nelson', 'Subregion': 'Nelson'},
        {'Country': 'New Zealand', 'Region': 'Wellington', 'Subregion': 'Martinborough'},
        {'Country': 'Portugal', 'Region': 'Alentejo', 'Subregion': 'Alentejo'},
        {'Country': 'Portugal', 'Region': 'Alentejo', 'Subregion': 'Setúbal'},
        {'Country': 'Portugal', 'Region': 'Alentejo', 'Subregion': 'Vinho Regional Alentejo'},
        {'Country': 'Portugal', 'Region': 'Douro', 'Subregion': 'Douro'},
        {'Country': 'Portugal', 'Region': 'Minho', 'Subregion': 'IGP Minho'},
        {'Country': 'Portugal', 'Region': 'Central Region', 'Subregion': 'Bairrada'},
        {'Country': 'Portugal', 'Region': 'Central Region', 'Subregion': 'Beira Interior'},
        {'Country': 'Portugal', 'Region': 'Central Region', 'Subregion': 'Dão'},
        {'Country': 'Portugal', 'Region': 'North Region', 'Subregion': 'Vinho Verde'},
        {'Country': 'Portugal', 'Region': 'Acores', 'Subregion': 'IG Açores'},
        {'Country': 'Portugal', 'Region': 'Acores', 'Subregion': 'Pico'},
        {'Country': 'Portugal', 'Region': 'Lisboa', 'Subregion': 'IG Lisboa'},
        {'Country': 'Portugal', 'Region': 'Porto', 'Subregion': 'Porto'},
        {'Country': 'Portugal', 'Region': 'Portugal', 'Subregion': 'Vinho Portugal'},
        {'Country': 'Slovenia', 'Region': 'Primorska', 'Subregion': 'Goriška Brda'},
        {'Country': 'Slovenia', 'Region': 'Primorska', 'Subregion': 'Vipava Valley'},
        {'Country': 'South Africa', 'Region': 'Western Cape', 'Subregion': 'Cape South Coast'},
        {'Country': 'South Africa', 'Region': 'Western Cape', 'Subregion': 'Elgin Valley'},
        {'Country': 'South Africa', 'Region': 'Western Cape', 'Subregion': 'Franschhoek'},
        {'Country': 'South Africa', 'Region': 'Western Cape', 'Subregion': 'Klein River'},
        {'Country': 'South Africa', 'Region': 'Western Cape', 'Subregion': 'Robertson'},
        {'Country': 'South Africa', 'Region': 'Western Cape', 'Subregion': 'Stellenbosch'},
        {'Country': 'South Africa', 'Region': 'Western Cape', 'Subregion': 'Swartland'},
        {'Country': 'South Africa', 'Region': 'Western Cape', 'Subregion': 'Walker Bay'},
        {'Country': 'Spain', 'Region': 'Andalucia', 'Subregion': 'Condado de Huelva'},
        {'Country': 'Spain', 'Region': 'Andalucia', 'Subregion': 'IGP Cádiz'},
        {'Country': 'Spain', 'Region': 'Andalucia', 'Subregion': 'IGP Sierra Norte de Sevilla'},
        {'Country': 'Spain', 'Region': 'Andalucia', 'Subregion': 'Jerez-Xérès-Sherry'},
        {'Country': 'Spain', 'Region': 'Andalucia', 'Subregion': 'Lebrija'},
        {'Country': 'Spain', 'Region': 'Andalucia', 'Subregion': 'Manzanilla-Sanlúcar de Barrameda'},
        {'Country': 'Spain', 'Region': 'Andalucia', 'Subregion': 'Montilla-Moriles'},
        {'Country': 'Spain', 'Region': 'Andalucia', 'Subregion': 'Málaga'},
        {'Country': 'Spain', 'Region': 'Andalucia', 'Subregion': 'Sierras de Málaga'},
        {'Country': 'Spain', 'Region': 'Aragon', 'Subregion': 'Aylés'},
        {'Country': 'Spain', 'Region': 'Aragon', 'Subregion': 'Calatayud'},
        {'Country': 'Spain', 'Region': 'Aragon', 'Subregion': 'Campo de Borja'},
        {'Country': 'Spain', 'Region': 'Aragon', 'Subregion': 'Cariñena'},
        {'Country': 'Spain', 'Region': 'Aragon', 'Subregion': 'IGP Bajo Aragón'},
        {'Country': 'Spain', 'Region': 'Aragon', 'Subregion': 'IGP Ribera del Queiles'},
        {'Country': 'Spain', 'Region': 'Aragon', 'Subregion': 'IGP Valdejalón'},
        {'Country': 'Spain', 'Region': 'Aragon', 'Subregion': 'Somontano'},
        {'Country': 'Spain', 'Region': 'Asturias', 'Subregion': 'Cangas'},
        {'Country': 'Spain', 'Region': 'Cantabria', 'Subregion': 'IGP Costa de Cantabria'},
        {'Country': 'Spain', 'Region': 'Catalonia', 'Subregion': 'Alella'},
        {'Country': 'Spain', 'Region': 'Catalonia', 'Subregion': 'Cataluña'},
        {'Country': 'Spain', 'Region': 'Catalonia', 'Subregion': 'Conca de Barberà'},
        {'Country': 'Spain', 'Region': 'Catalonia', 'Subregion': 'Costers del Sagre'},
        {'Country': 'Spain', 'Region': 'Catalonia', 'Subregion': 'Empordà'},
        {'Country': 'Spain', 'Region': 'Catalonia', 'Subregion': 'Montsant'},
        {'Country': 'Spain', 'Region': 'Catalonia', 'Subregion': 'Penedés'},
        {'Country': 'Spain', 'Region': 'Catalonia', 'Subregion': 'Pla de Bages'},
        {'Country': 'Spain', 'Region': 'Catalonia', 'Subregion': 'Priorat'},
        {'Country': 'Spain', 'Region': 'Catalonia', 'Subregion': 'Tarragona'},
        {'Country': 'Spain', 'Region': 'Catalonia', 'Subregion': 'Terre Alta'},
        {'Country': 'Spain', 'Region': 'Castilla la Mancha', 'Subregion': 'Almansa'},
        {'Country': 'Spain', 'Region': 'Castilla la Mancha', 'Subregion': 'Campo de la Guardia'},
        {'Country': 'Spain', 'Region': 'Castilla la Mancha', 'Subregion': 'Casa del Blanco'},
        {'Country': 'Spain', 'Region': 'Castilla la Mancha', 'Subregion': 'Chozas Carrascal'},
        {'Country': 'Spain', 'Region': 'Castilla la Mancha', 'Subregion': 'Dehesa del Carrizal'},
        {'Country': 'Spain', 'Region': 'Castilla la Mancha', 'Subregion': 'Dominio de Valdepusa'},
        {'Country': 'Spain', 'Region': 'Castilla la Mancha', 'Subregion': 'IGP Castilla'},
        {'Country': 'Spain', 'Region': 'Castilla la Mancha', 'Subregion': 'La Mancha'},
        {'Country': 'Spain', 'Region': 'Castilla la Mancha', 'Subregion': 'Manchuela'},
        {'Country': 'Spain', 'Region': 'Castilla la Mancha', 'Subregion': 'Méntrida'},
        {'Country': 'Spain', 'Region': 'Castilla la Mancha', 'Subregion': 'Pago Calzadilla'},
        {'Country': 'Spain', 'Region': 'Castilla la Mancha', 'Subregion': 'Pago del Vicario'},
        {'Country': 'Spain', 'Region': 'Castilla la Mancha', 'Subregion': 'Pago Finca Élez'},
        {'Country': 'Spain', 'Region': 'Castilla la Mancha', 'Subregion': 'Pago Florentino'},
        {'Country': 'Spain', 'Region': 'Castilla la Mancha', 'Subregion': 'Pago Vallegarcia'},
        {'Country': 'Spain', 'Region': 'Castilla la Mancha', 'Subregion': 'Uclés'},
        {'Country': 'Spain', 'Region': 'Castilla la Mancha', 'Subregion': 'Valdepeñas'},
        {'Country': 'Spain', 'Region': 'Castilla y Leon', 'Subregion': 'Arlanza'},
        {'Country': 'Spain', 'Region': 'Castilla y Leon', 'Subregion': 'Arribes'},
        {'Country': 'Spain', 'Region': 'Castilla y Leon', 'Subregion': 'Bierzo'},
        {'Country': 'Spain', 'Region': 'Castilla y Leon', 'Subregion': 'Cebreros'},
        {'Country': 'Spain', 'Region': 'Castilla y Leon', 'Subregion': 'Cigales'},
        {'Country': 'Spain', 'Region': 'Castilla y Leon', 'Subregion': 'IGP Castilla y León'},
        {'Country': 'Spain', 'Region': 'Castilla y Leon', 'Subregion': 'León'},
        {'Country': 'Spain', 'Region': 'Castilla y Leon', 'Subregion': 'Ribera del Duero'},
        {'Country': 'Spain', 'Region': 'Castilla y Leon', 'Subregion': 'Rueda'},
        {'Country': 'Spain', 'Region': 'Castilla y Leon', 'Subregion': 'Sierra de Salamanca'},
        {'Country': 'Spain', 'Region': 'Castilla y Leon', 'Subregion': 'Tierra del Vino de Zamora'},
        {'Country': 'Spain', 'Region': 'Castilla y Leon', 'Subregion': 'Toro'},
        {'Country': 'Spain', 'Region': 'Extremadura', 'Subregion': 'IGP Extremadura'},
        {'Country': 'Spain', 'Region': 'Extremadura', 'Subregion': 'Ribera del Guadiana'},
        {'Country': 'Spain', 'Region': 'Galicia', 'Subregion': 'IGP Barbanza e Iria'},
        {'Country': 'Spain', 'Region': 'Galicia', 'Subregion': 'Monterrei'},
        {'Country': 'Spain', 'Region': 'Galicia', 'Subregion': 'Ribeira Sacra'},
        {'Country': 'Spain', 'Region': 'Galicia', 'Subregion': 'Ribeiro'},
        {'Country': 'Spain', 'Region': 'Galicia', 'Subregion': 'Rias Baixas'},
        {'Country': 'Spain', 'Region': 'Galicia', 'Subregion': 'Valdeorras'},
        {'Country': 'Spain', 'Region': 'Islas Baleares', 'Subregion': 'Binissalem'},
        {'Country': 'Spain', 'Region': 'Islas Baleares', 'Subregion': 'IGP Formentera'},
        {'Country': 'Spain', 'Region': 'Islas Baleares', 'Subregion': 'IGP Mallorca'},
        {'Country': 'Spain', 'Region': 'Islas Canarias', 'Subregion': 'Abona'},
        {'Country': 'Spain', 'Region': 'Islas Canarias', 'Subregion': 'La Palma'},
        {'Country': 'Spain', 'Region': 'Islas Canarias', 'Subregion': 'Lanzarote'},
        {'Country': 'Spain', 'Region': 'Islas Canarias', 'Subregion': 'Tacoronte-Acentejo'},
        {'Country': 'Spain', 'Region': 'Islas Canarias', 'Subregion': 'Valle de Gueímar'},
        {'Country': 'Spain', 'Region': 'Islas Canarias', 'Subregion': 'Valle de la Orotava'},
        {'Country': 'Spain', 'Region': 'Madrid', 'Subregion': 'Vinos de Madrid'},
        {'Country': 'Spain', 'Region': 'Murcia', 'Subregion': 'Bullas'},
        {'Country': 'Spain', 'Region': 'Murcia', 'Subregion': 'Jumilla'},
        {'Country': 'Spain', 'Region': 'Murcia', 'Subregion': 'Yecla'},
        {'Country': 'Spain', 'Region': 'Navarra', 'Subregion': 'Finca Bolandin'},
        {'Country': 'Spain', 'Region': 'Navarra', 'Subregion': 'IGP 3 Riberas'},
        {'Country': 'Spain', 'Region': 'Navarra', 'Subregion': 'Navarra'},
        {'Country': 'Spain', 'Region': 'Navarra', 'Subregion': 'Pago de Arinzano'},
        {'Country': 'Spain', 'Region': 'Pais Vasco', 'Subregion': 'Txakoli de Bizkaia'},
        {'Country': 'Spain', 'Region': 'Pais Vasco', 'Subregion': 'Txakoli de Getaria'},
        {'Country': 'Spain', 'Region': 'Pais Vasco', 'Subregion': 'Txakoli de Álava'},
        {'Country': 'Spain', 'Region': 'Rioja', 'Subregion': 'IGP Valles de Sadacia'},
        {'Country': 'Spain', 'Region': 'Rioja', 'Subregion': 'Rioja'},
        {'Country': 'Spain', 'Region': 'Spain', 'Subregion': 'Cava'},
        {'Country': 'Spain', 'Region': 'Spain', 'Subregion': 'España'},
        {'Country': 'Spain', 'Region': 'Spain', 'Subregion': 'Vino de España'},
        {'Country': 'Spain', 'Region': 'Valencia', 'Subregion': 'Alicante'},
        {'Country': 'Spain', 'Region': 'Valencia', 'Subregion': 'El Terrerazo'},
        {'Country': 'Spain', 'Region': 'Valencia', 'Subregion': 'Los Balagueses'},
        {'Country': 'Spain', 'Region': 'Valencia', 'Subregion': 'Pago de Tharsys'},
        {'Country': 'Spain', 'Region': 'Valencia', 'Subregion': 'Utiel-Requena'},
        {'Country': 'Spain', 'Region': 'Valencia', 'Subregion': 'Valencia'},
        {'Country': 'Swiss', 'Region': 'Valais', 'Subregion': 'Valais'},
        {'Country': 'Uruguay', 'Region': 'Canelones', 'Subregion': 'Canelones Melilla'},
        {'Country': 'Uruguay', 'Region': 'Montevideo', 'Subregion': 'Montevideo'},
        {'Country': 'USA', 'Region': 'California', 'Subregion': 'California'},
        {'Country': 'USA', 'Region': 'California', 'Subregion': 'Lodi'},
        {'Country': 'USA', 'Region': 'California', 'Subregion': 'Napa Valley'},
        {'Country': 'USA', 'Region': 'California', 'Subregion': 'River Junction'},
        {'Country': 'USA', 'Region': 'California', 'Subregion': 'Sonoma County'},
        {'Country': 'USA', 'Region': 'Oregon', 'Subregion': 'Willamette Valley'},
        {'Country': 'USA', 'Region': 'Washington', 'Subregion': 'Washington'},
        {'Country': 'USA', 'Region': 'Washington', 'Subregion': 'Yakima Valley'}
        ]

    new_c = ''
    new_r = ''
    new_s = ''

    for place in region_list:
        if r == place['Subregion']:
            new_c = place['Country']
            new_r = place['Region']
            new_s = place['Subregion']
        else:
            for place in region_list:
                if r == place['Region']:
                    new_c = place['Country']
                    new_r = place['Region']
                    new_s = place['Subregion']
                else:
                    pass

    return new_c, new_r, new_s
